version: '3'
services:
  web:
    image: nginx
    volumes:
      - ./docker/nginx/default.conf:/etc/nginx/conf.d/default.conf
      - .:/var/www/html
    ports:
      - 8080:80
    restart: always
    depends_on:
      - php-fpm
  php-fpm:
    build:
      context: docker
      dockerfile: php-fpm.docker
    restart: always
    volumes:
      - .:/var/www/html
    env_file:
      - .env
  rabbitmq:
      image: rabbitmq:3.10.7-management
      hostname: rabbitmq
      environment:
          - RABBITMQ_DEFAULT_USER=${RABBITMQ_USER}
          - RABBITMQ_DEFAULT_PASS=${RABBITMQ_PASSWORD}
          - RABBITMQ_DEFAULT_VHOST=/
          - RABBITMQ_SERVER_ADDITIONAL_ERL_ARGS=-rabbit log_levels [{connection,error},{default,error}] disk_free_limit 2147483648
      volumes:
          - ./rabbitmq:/var/lib/rabbitmq
      ports:
          - 15672:15672
          - 5672:5672

#  scheduler:
#        build:
#            context: docker
#            dockerfile: php-fpm.docker
#        command: ["php", "/var/www/html/artisan", "schedule:work"]
